src/mySite/dataVis/urls.py
from django.conf.urls import url

from . import views


app_name='dataVis'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^plot1d/$', views.Plot1DView.as_view(), name='plot1d'),
    url(r'^plot2d/$', views.Plot2DView.as_view(), name='plot2d'),
    url(r'^plot3d/$', views.Plot3DView.as_view(), name='plot3d'),
    url(r'^plot1d_multiple/(?P<n>\d+)/$',
        views.Plot1DMultipleView.as_view(), name='plot1d_multiple'),
    url(r'^plot1d_multiple_ajax/(?P<n>\d+)/$',
        views.plot1d_multiple_ajax, name='plot1d_multiple_ajax'),
    url(r'^plotIq/$', views.PlotIqView.as_view(), name='plotIq'),
    url(r'^plot_live/$', views.PlotLiveView.as_view(), name='plot_live'),
    url(r'^plot_live_update/$', views.plot_live_update, name='plot_live_update'),
    url(r'^plot3d_scatter/$', views.Plot3DScatterView.as_view(), name='plot3d_scatter'),
]

src/mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/dataVis/'), name='index'),
    path('dataVis/',  include('dataVis.urls')),
]

src/mySite/dataVis/models.py
from django.db import models

# Create your models here.

src/mySite/dataVis/views.py
import logging

from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.views.generic import TemplateView

from . import plots

logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = "index.html"


class Plot1DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot1DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot1d()
        return context


class Plot2DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot2DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot2d()
        return context


class Plot3DView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3d()
        return context


class Plot1DMultipleView(TemplateView):
    template_name = "plot_multiple.html"

    def get_context_data(self, **kwargs):
        n = int(kwargs['n'])
        # Call the base implementation first to get a context
        context = super(Plot1DMultipleView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot1d_multiple(n)
        return context


def plot1d_multiple_ajax(request, n):
    """
    Only handles AJAX queries
    """
    logger.debug("Plotting {} plots.".format(n))
    return HttpResponse(plots.plot1d_multiple(int(n)))


class PlotIqView(TemplateView):
    template_name = "plot_fit.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PlotIqView, self).get_context_data(**kwargs)
        context['plot'] = plots.plotIq()
        return context


class PlotLiveView(TemplateView):
    template_name = "plot_live.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PlotLiveView, self).get_context_data(**kwargs)
        context['plot'] = plots.plotLive()
        return context


def plot_live_update(request):
    '''
    Handle ajax call to update the live plot
    '''
    if request.is_ajax():
        logger.debug("Live plot updated...")
        data = plots.live_plot_get_data_serialized()
        # In order to allow non-dict objects to be serialized set the safe
        # parameter to False
        return JsonResponse([data], safe=False)
    else:
        return HttpResponseBadRequest()

class Plot3DScatterView(TemplateView):
    template_name = "plot.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Plot3DScatterView, self).get_context_data(**kwargs)
        context['plot'] = plots.plot3D_scatter
        return context

src/mySite/dataVis/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <title>Django Interactive Data Visualization</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  {% endblock %}
</head>
<body>
  {% block content %}
  <!-- Content goes here -->

  {% endblock %}

  {% block tail %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  {% endblock %}
</body>
</html>

src/mySite/dataVis/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h1>Django Interactive Data Visualization</h1>
  <p class="lead">Click on the buttons below to see the examples.</p>
</div>

<div class="container">
  <table class="table table-striped table-hover">
    <tr>
      <td>1D</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plot1d' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>2D</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plot2d' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plot3d' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>Random 1D (Ajax)</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plot1d_multiple' 1 %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>SANS Iq</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plotIq' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>Live Plot 2D</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plot_live' %}" role="button">View</a></td>
    </tr>
    <tr>
      <td>3D Scatter</td>
      <td><a class="btn btn-default" href="{% url 'dataVis:plot3d_scatter' %}" role="button">View</a></td>
    </tr>
  </table>
</div>
<!-- /.container -->

{% endblock %}

src/mySite/dataVis/templates/plot.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Interactive Data Visualization</h1>
  <!--<p class="lead">Here we go...</p>-->
  <hr>
</div>

<!-- /.container -->

<div class="container">
  <div class="row" style="border: 1px solid black">
    {# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
    <div class="col-md-12">{{plot|safe}}</div>
  </div>
</div>
<!-- /.container -->


<div class="container">
  <hr>
  <!--<p>-->
    <!--&nbsp;-->
  <!--</p>-->
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>

{% endblock %}

src/mySite/dataVis/templates/plot_fit.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Interactive Data Visualization + JavaScript</h1>
  <p class="lead">Select some points (Box or Lasso tool) from the plot and see them printed.</p>
</div>

<div class="container">
  <div class="row" style="border: 1px solid black">
    <div id="plot_container" class="col-md-12">{{plot|safe}}</div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <br/>
    </div>
  </div>
</div>

<!--<div class="container">-->
  <!--<div class="row">-->
    <!--<div class="col-md-12">-->
      <!--<pre>-->
        <!--var myDiv = $('.plotly-graph-div')[0];-->
        <!--myDiv.on('plotly_selected', function(eventData) {-->
          <!--console.log(eventData.points);-->
          <!--for (var idx = 0; idx < eventData.points.length; idx++) {-->
            <!--console.log(eventData.points[idx]);-->
          <!--};-->
        <!--});-->
      <!--</pre>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->

<div class="container">
  <p>Selected points:</p>
  <pre id="selected_points">

  </pre>
</div>

<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
<!-- /.container -->
{% endblock %}

{% block tail %}
{{block.super}}
<script>
    var myDiv = $('.plotly-graph-div')[0];
    myDiv.on('plotly_selected', function(eventData) {
      console.log(eventData.points);
      $("#selected_points").empty();
      for (var idx = 0; idx < eventData.points.length; idx++) {
        // console.log(eventData.points[idx]);
        $("#selected_points").append(
          "<strong>" + eventData.points[idx].data.name + "</strong>=(" + eventData.points[idx].x + "," + eventData.points[idx].y + ") "
        );
      };
    });
</script>
{% endblock %}

src/mySite/dataVis/templates/plot_live.html
{% extends "base.html" %}
{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
    <h1>Live 2D Interactive Data Visualization</h1>
    <p class="lead">Update every few seconds</p>
    <hr>
</div>
<!-- /.container -->

<div class="container">
  <div class="row">
    <div class="col-md-12">{{plot|safe}}</div>
  </div>
</div>
<!-- /.container -->
<hr>
<div class="container">
  <p>
    &nbsp;
  </p>
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
<!-- /.container -->

<script type="text/javascript">
    (function poll() {
        setTimeout(function() {
            $.ajax({
                type: "GET",
                url: "{% url 'dataVis:plot_live_update' %}",
                success: function(data) {
                    var plot_div = $('.plotly-graph-div')[0];
                    // If the new data is an update to the old one
                    // var old_data = plot_div.data;
                    // old_data[0].x = old_data[0].x.concat(data[0].x);
                    // old_data[0].y = old_data[0].y.concat(data[0].y);
                    // Plotly.newPlot(plot_div,old_data, plot_div.layout);
                    Plotly.newPlot(plot_div,data, plot_div.layout);
                },
                dataType: "json",
                complete: poll,
                timeout: 2000
            })
        }, 1000);
    })();
</script>


{% endblock %}

src/mySite/dataVis/templates/plot_multiple.html
{% extends "base.html" %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
  <h1>Random 1D Interactive Data Visualization</h1>
  <hr>

  <!--<p class="lead">Ajax test!</p>-->
</div>
<!-- /.container -->

<div class="container">
  <div class="row">
    <div class="col-md-12"><div id="plot">{{plot|safe}}</div></div>
  </div>
</div>
<!-- /.container -->
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <button id="button" type="button" class="btn btn-primary" data-loading-text="Loading..." >Click To Change number of graphics</button>
      <div id=time></div>
    </div>
  </div>
</div>
<!-- /.container -->

<div class="container">

  <!--<p>-->
    <!--&nbsp;-->
  <!--</p>-->
  <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
{% endblock %}

{% block tail %}
{{block.super}}
<script>
// Set up the buttons
$("#button").click(function() {
  var btn = $(this);
  btn.button('loading');
  // Then whatever you actually want to do i.e. submit form
  // After that has finished, reset the button state using
  var n = Math.floor((Math.random() * 50) + 1);
  $.ajax({
    url: "{% url 'dataVis:plot1d_multiple_ajax' n=1234 %}".replace('1234',""+n),
    type: 'get', // This is the default though, you don't actually need to always mention it
    success: function(data) {
        $('#plot').empty().append(data);
        btn.button('reset');
    },
    failure: function(data) {
        alert('Got an error dude!');
        btn.button('reset');
    },
    start_time: new Date().getTime(),
    complete: function(data) {
        var message = 'Time: '+(new Date().getTime() - this.start_time)+' ms for ' + n + ' lines.';
        // console.log(message);
        $("#time").html('<br/><p class="lead">' + message + '</p>');
    }
  });

});
</script>
{% endblock %}